### ISSUE TITLE
Crashes on launch (outdated kiss3d version?)

### ISSUE THREAD

**Issue by maybeetree** [bddap/watch-stl-rust#4]
Following the instructions in the README results in a successful compilation, but actually using the binary to view STL files results in a crash. Here is the command invocation and stack trace:

```
$ RUST_BACKTRACE=full target/release/watch-stl samples/bunny_99.stl
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState<'_>` uninitialized, which is invalid', /home/maybetree/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/x11/util/input.rs:94:51
stack backtrace:
   0:     0x55877227073a - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55877227073a - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55877227073a - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55877227073a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55877229232e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x55877226d945 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x558772270505 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x558772270505 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x558772271cef - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x558772271a2b - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x5587722723fc - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x558772272152 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:577:13
  12:     0x558772270bec - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x558772271ea2 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x558772101763 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x55877210183d - core::panicking::panic::h545818946343732b
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
  16:     0x558772196100 - winit::platform::platform::x11::window::UnownedWindow::new::h809b2a1b0da6d28e
  17:     0x55877217cc92 - winit::platform::platform::x11::Window::new::h10117e8a7cd1046b
  18:     0x55877216d57a - glutin::platform::platform::x11::Context::new::h42f49a126265e761
  19:     0x55877216961c - glutin::platform::platform::Context::new::h73db5531307e89ee
  20:     0x5587721698e5 - glutin::GlWindow::new::h1d8f1e5edbb1aad7
  21:     0x5587721334f2 - <kiss3d::window::gl_canvas::GLCanvas as kiss3d::window::canvas::AbstractCanvas>::open::h948645bbdd69681a
  22:     0x5587721474b9 - kiss3d::window::window::Window::do_new::h816c026a3fd37632
  23:     0x558772147353 - kiss3d::window::window::Window::new::h28f8027647de8716
  24:     0x55877210a9ed - watch_stl::main::h78208642479a1b7f
  25:     0x55877210c183 - std::sys_common::backtrace::__rust_begin_short_backtrace::h594e1e3a3ddda63c
  26:     0x55877210c199 - std::rt::lang_start::{{closure}}::h1d3afe69368cbb7b
  27:     0x55877226968c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  28:     0x55877226968c - std::panicking::try::do_call::h0497133ebe1341e5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  29:     0x55877226968c - std::panicking::try::h6c3de05c7ca5d07f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  30:     0x55877226968c - std::panic::catch_unwind::h969058ecb5334b30
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  31:     0x55877226968c - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  32:     0x55877226968c - std::panicking::try::do_call::h77301dcf43953993
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  33:     0x55877226968c - std::panicking::try::h45b05523a2fe135a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  34:     0x55877226968c - std::panic::catch_unwind::hd95cea544b2b9bd2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  35:     0x55877226968c - std::rt::lang_start_internal::hd16e6ff7bf05a444
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  36:     0x55877210b0b5 - main
  37:     0x7f6318e5c20c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  38:     0x7f6318e5c2bc - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  39:     0x558772101d21 - _start
                               at ./csu/../sysdeps/x86_64/start.S:115
  40:                0x0 - <unknown>

```

This appears to be a bug in an old version of `winit`, which is an indirect dependency of `kiss3d`. Perhaps updating to the latest kiss3d might help? I tried changing the kiss3d version in `Cargo.toml`, as well as the `winit` version with `patch`, but I kept running into compilation errors that I couldn't fix (I am not a rust dev).

If it helps, I am running Linux with X11 and BSPWM window manager.

**Comment by bddap** [comment]
Happy to see some interest in this project!

I've updated the dependencies on the main branch.

**Comment by maybeetree** [comment]
Thanks so much, it works now!!
I'm running into a different issue now tho, whenever the stl file is updated, instead of fully reloading the model, it just plonks down the new model on top of the old one, such that both are visible. I'm going to open a new issue for this.
